### ISSUE TITLE
No valid parser available.

### ISSUE THREAD

**Issue by him0** [labra/shaclex#7] opened 2016-11-22 17:47 UTC
`$ sbt test` command works good, but `$ sbt run -d src/test/resources/shacl/core/example1.ttl` cause error.

```
$ sbt run -d src/test/resources/shacl/core/example1.ttl 
[residual] arg = 'src/test/resources/shacl/core/example1.ttl'
[residual] arg = 'run'
[residual] arg = 'src/test/resources/shacl/core/example1.ttl'
[process_args] java_version = '1.8.0_92'
# Executing command line:
java
-Xms1024m
-Xmx1024m
-XX:ReservedCodeCacheSize=128m
-XX:MaxMetaspaceSize=256m
-jar
/usr/local/Cellar/sbt/0.13.13/libexec/sbt-launch.jar
run
src/test/resources/shacl/core/example1.ttl

[info] Loading project definition from /Users/user/src/shaclex/project/project
[info] Loading project definition from /Users/user/src/shaclex/project
[info] Set current project to shaclex (in build file:/Users/user/src/shaclex/)
[info] Running es.weso.shaclex.Main 
02:41:58.108 [run-main-0] INFO  es.weso.shaclex.Main$ - RDF Data option not specified
02:41:58.766 [run-main-0] INFO  es.weso.shaclex.Main$ - Schema not specified. Extracting schema from data
02:41:58.768 [run-main-0] ERROR es.weso.shaclex.Main$ - Exception: Not implemented get ShEx from RDF yet
[success] Total time: 5 s, completed 2016/11/23 2:41:58
[error] No valid parser available.
[error] src/test/resources/shacl/core/example1.ttl
[error]     ^
```

**Comment by labra** [comment] 2016-11-23 16:36
Thanks for your report.  Are you using the latest version in master? Because I got a different error.

Anyway, the problem is that the command line is trying to support both ShEx and SHACL. In this case, it seems that you want to validate using SHACL. To do so, you should add the option `--engine SHACLEX`

So the call should be:

```
run -d src/test/resources/shacl/core/example1.ttl --engine SHACLEX
```

Otherwise, at this moment, the default engine is `ShEx` and if you don't provie a schema, it tries to collect the schema from the RDF file, an option that has not been implemented yet for ShEx. In the future, if we agree on an RDF serialization for ShEx, it should be possible to incllude both the data and the schema in RDF, that's why I keep that option available.

Anyway, I will keep the issue open by now until I can revisit the documentation to add some explanation of this behaviour.

**Comment by labra** [comment] 2016-11-24 06:43
I have changed the behaviour of the command line to return an empty ShEx schema when no schema is specified.

In the future, it would be better to have an RDF -> ShEx converter that can extract the schema from the RDF. 

It was already implemented in ShExcala so it should not be difficult, although it would be better to define the translation in a standard way so all ShEx implementations used the same RDF vocabulary

**Comment by labra** [comment] 2016-11-24 06:49
I close this issue because I have created a specific issue for ShEx RDF serialization at #8

**Closed by labra** 2016-11-24 06:49 UTC

**Comment by him0** [comment] 2016-11-25 05:11
Thank you for response!

I'm using the latest version in master. I want to validate the RDF document with using shacl, but it still not work!

it seemed the option argument '-d' is not detected. Does this problem cause on only my environment?

```
$ sbt run -d src/test/resources/shacl/core/example1.ttl --engine SHACLEX
[residual] arg = 'src/test/resources/shacl/core/example1.ttl'
[residual] arg = '--engine'
[residual] arg = 'SHACLEX'
[residual] arg = 'run'
[residual] arg = 'src/test/resources/shacl/core/example1.ttl'
[residual] arg = '--engine'
[residual] arg = 'SHACLEX'
[process_args] java_version = '1.8.0_92'
# Executing command line:
java
-Xms1024m
-Xmx1024m
-XX:ReservedCodeCacheSize=128m
-XX:MaxMetaspaceSize=256m
-jar
/usr/local/Cellar/sbt/0.13.13/libexec/sbt-launch.jar
run
src/test/resources/shacl/core/example1.ttl
--engine
SHACLEX

[info] Loading project definition from /Users/user/src/shaclex/project/project
[info] Loading project definition from /Users/user/src/shaclex/project
[info] Set current project to shaclex (in build file:/Users/user/src/shaclex/)
[info] Running es.weso.shaclex.Main 
13:58:28.510 [run-main-0] INFO  es.weso.shaclex.Main$ - RDF Data option not specified
13:58:29.138 [run-main-0] INFO  es.weso.shaclex.Main$ - Schema not specified. Extracting schema from data
13:58:29.140 [run-main-0] WARN  es.weso.schema.ShExSchema - Not implemented conversion from RDF. Returns empty Schema

[success] Total time: 6 s, completed 2016/11/25 13:58:29
[error] No valid parser available.
[error] src/test/resources/shacl/core/example1.ttl
[error]     ^
```

**Comment by labra** [comment] 2016-11-25 06:46
You need to add quotes to the `run args` command. Try this:

```
sbt "run -d src/test/resources/shacl/core/example1.ttl --engine SHACLEX"
```

**Comment by him0** [comment] 2016-11-25 06:53
Thank you! It works! README shows the following 2 example commands.

```
sbt run -d examples/good1.ttl
sbt run -e ShEx -s examples/shex/good1.shex --schemaFormat ShExC -d examples/shex/good1.ttl
```

Shall I make the fix pull request?

**Comment by labra** [comment] 2016-11-25 09:02
Ah, you are right. Of course, if you want to help doing the pull request, that would be great. 

I also think I moved the SHACL examples to the folder `examples/shacl/good1.ttl`

Thanks for using Shaclex!
